export const REQUEST_PATIENTS = 'REQUEST_PATIENTS'
export const RECEIVE_PATIENTS = 'RECEIVE_PATIENTS'

export const REQUEST_PATIENT_CONDITIONS = 'REQUEST_PATIENT_CONDITIONS'
export const RECEIVE_PATIENT_CONDITIONS = 'RECEIVE_PATIENT_CONDITIONS'

export const REQUEST_PATIENT_OBSERVATIONS = 'REQUEST_PATIENT_OBSERVATIONS'
export const RECEIVE_PATIENT_OBSERVATIONS = 'RECEIVE_PATIENT_OBSERVATIONS'

export const REQUEST_PATIENT_IMMUNIZATIONS = 'REQUEST_PATIENT_IMMUNIZATIONS'
export const RECEIVE_PATIENT_IMMUNIZATIONS = 'RECEIVE_PATIENT_IMMUNIZATIONS'

export const REQUEST_PATIENT_GLUCOSE_SUMMARY = 'REQUEST_PATIENT_GLUCOSE_SUMMARY'
export const RECEIVE_PATIENT_GLUCOSE_SUMMARY = 'RECEIVE_PATIENT_GLUCOSE_SUMMARY'

export const ADD_PATIENT_DAILY_REPORT = 'ADD_PATIENT_DAILY_REPORT'
export const CLEAR_PATIENT_DAILY_GLUCOSE_OVERVIEW = 'CLEAR_PATIENT_DAILY_GLUCOSE_OVERVIEW'

export const SELECT_PATIENT = 'SELECT_PATIENT'
export const SELECT_PATIENT_SUBMENU = 'SELECT_PATIENT_SUBMENU'

export const SELECT_MENU = 'SELECT_MENU'